// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilenioRadartonaAPI.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MilenioRadartonaAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191226194958_Lucas")]
    partial class Lucas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MilenioRadartonaAPI.Models.Caminhao", b =>
                {
                    b.Property<int>("CaminhaoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Placa");

                    b.HasKey("CaminhaoId");

                    b.ToTable("Caminhoes");
                });

            modelBuilder.Entity("MilenioRadartonaAPI.Models.Chave", b =>
                {
                    b.Property<int>("ChaveId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Authenticated");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Expiration");

                    b.Property<string>("Message");

                    b.Property<string>("Token");

                    b.Property<int>("UsuarioId");

                    b.HasKey("ChaveId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Chave");
                });

            modelBuilder.Entity("MilenioRadartonaAPI.Models.Mensagem", b =>
                {
                    b.Property<int>("MensagemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaminhaoId");

                    b.Property<string>("Corpo");

                    b.Property<DateTime>("DataHora");

                    b.Property<string>("LinkAudio");

                    b.Property<string>("Sender");

                    b.Property<int>("UsuarioId");

                    b.HasKey("MensagemId");

                    b.HasIndex("CaminhaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("MilenioRadartonaAPI.Models.RequisicaoInfos", b =>
                {
                    b.Property<int>("RequisicaoInfosId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DiaRequisicao");

                    b.Property<int>("QtdReqDiaMax");

                    b.Property<int>("QtdReqFeitasNoDia");

                    b.Property<int>("UsuarioId");

                    b.HasKey("RequisicaoInfosId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Requisicoes");
                });

            modelBuilder.Entity("MilenioRadartonaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Bloqueado");

                    b.Property<string>("Celular");

                    b.Property<DateTime>("CriacaoDeConta");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<int>("ReqInfosId");

                    b.Property<string>("TipoUsuario");

                    b.Property<DateTime>("UltimaMudancaDeSenha");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MilenioRadartonaAPI.Models.Chave", b =>
                {
                    b.HasOne("MilenioRadartonaAPI.Models.Usuario", "Usuario")
                        .WithOne("Chave")
                        .HasForeignKey("MilenioRadartonaAPI.Models.Chave", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MilenioRadartonaAPI.Models.Mensagem", b =>
                {
                    b.HasOne("MilenioRadartonaAPI.Models.Caminhao", "Caminhao")
                        .WithMany()
                        .HasForeignKey("CaminhaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MilenioRadartonaAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MilenioRadartonaAPI.Models.RequisicaoInfos", b =>
                {
                    b.HasOne("MilenioRadartonaAPI.Models.Usuario", "Usuario")
                        .WithMany("ReqInfos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
